//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAFTY1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int O_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string O_Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
