//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAFTY1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int S_ID { get; set; }
        public string Seller_Name { get; set; }
        public string Seller_Mail { get; set; }
        public string Seller_Phone { get; set; }
        public string Seller_Address { get; set; }
        public byte[] Seller_Image { get; set; }
    }
}
