//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRAFTY1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Admin
    {
        public int WA_ID { get; set; }
        public string Web_Admin_Name { get; set; }
        public string Web_Admin_Mail { get; set; }
        public string Web_Admin_Phone { get; set; }
        public string Web_Admin_Address { get; set; }
        public string Web_Admin_Password { get; set; }
        public byte[] Web_Admin_Image { get; set; }
    }
}
